### ISSUE TITLE
Unable to install the app

### ISSUE THREAD

**Issue by hypertrash** [vendetta-mod/Vendetta#133]
I am unable to download the app with the installer and it stops at downloading the app
Vendetta Manager v1.0.87
Built from commit cee4d01 on main (Changes Present)

Running Android 12, API level 31
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi

Checking if base-190017.apk is cached
base-190017.apk is not cached, downloading now

Failed on step DL_BASE_APK

java.lang.SecurityException: Unsupported path /data/data/dev.beefers.vendetta.manager/cache/190017/base-190017.apk
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2456)
	at android.os.Parcel.createException(Parcel.java:2440)
	at android.os.Parcel.readException(Parcel.java:2423)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
	at android.content.ContentResolver.insert(ContentResolver.java:2193)
	at android.content.ContentResolver.insert(ContentResolver.java:2155)
	at android.app.DownloadManager.enqueue(DownloadManager.java:1119)
	at dev.beefers.vendetta.manager.domain.manager.DownloadManager.download(DownloadManager.kt:110)
	at dev.beefers.vendetta.manager.domain.manager.DownloadManager.downloadDiscordApk(DownloadManager.kt:23)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.install(InstallerViewModel.kt:165)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.access$install(InstallerViewModel.kt:40)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel$job$1$1.invokeSuspend(InstallerViewModel.kt:106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
This is the copied logs

**Comment by hypertrash** [comment]
![Screenshot_20230816-000838](https://github.com/vendetta-mod/Vendetta/assets/82011716/99783fad-b6e8-45ce-86a6-2fb8341847da)

**Comment by daedaevibin** [comment]
This is being caused by device security protocols in java.lang.SecurityException

Devs please check validation of '/data/data/dev.beefers.vendetta.manager/cache/190017/base-190017.apk'


Added message for devs:



Fixing Unsupported Path Issue

Default (GPT-3.5)

User
How to fix

Checking if base-190017.apk is cached
base-190017.apk is not cached, downloading now

Failed on step DL_BASE_APK

java.lang.SecurityException: Unsupported path /data/data/dev.beefers.vendetta.manager/cache/190017/base-190017.apk
at android.os.Parcel.createExceptionOrNull(Parcel.java:2456)
at android.os.Parcel.createException(Parcel.java:2440)
at android.os.Parcel.readException(Parcel.java:2423)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
at android.content.ContentResolver.insert(ContentResolver.java:2193)
at android.content.ContentResolver.insert(ContentResolver.java:2155)
at android.app.DownloadManager.enqueue(DownloadManager.java:1119)
at dev.beefers.vendetta.manager.domain.manager.DownloadManager.download(DownloadManager.kt:110)
at dev.beefers.vendetta.manager.domain.manager.DownloadManager.downloadDiscordApk(DownloadManager.kt:23)
at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.install(InstallerViewModel.kt:165)
at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.access$install(InstallerViewModel.kt:40)
at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel$job$1$1.invokeSuspend(InstallerViewModel.kt:106)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

ChatGPT
The error message you provided seems to be a stack trace from a Java code snippet. It indicates that there's a java.lang.SecurityException occurring due to an unsupported path. It seems to be related to downloading and caching an APK file for an Android app.

To resolve this issue, you might want to check the following:

Permissions: Ensure that your app has the necessary permissions to access the storage and download files. You might need to request the WRITE_EXTERNAL_STORAGE permission in your AndroidManifest.xml.

Path Issues: Make sure that the paths you are using for caching and downloading the APK are correct and supported. The path /data/data/dev.beefers.vendetta.manager/cache/190017/base-190017.apk should be a valid location for caching, and the DownloadManager should be able to handle it.

Content Provider: The error seems to be related to inserting data into a content provider. Double-check that you're using the correct URI and content resolver to perform the insertion.

Exception Handling: Wrap the relevant code in try-catch blocks to handle any exceptions gracefully. This will help you identify the exact cause of the issue and provide a better error message.

Library Versions: Ensure that you are using the appropriate library versions for downloading and caching files. Outdated or incompatible libraries could potentially lead to such issues.

**Comment by hypertrash** [comment]
So am I just unable to do anything until the devs are involved?

**Comment by daedaevibin** [comment]
> So am I just unable to do anything until the devs are involved?

Quite frankly, yes.

**Comment by daedaevibin** [comment]
> So am I just unable to do anything until the devs are involved?

Do check your manager application for updates please. Thank you

**Comment by wingio** [comment]
First of all, don't use ChatGPT to solve issues, it's unable to help. Secondly can I ask what rom and device are you using

**Comment by hypertrash** [comment]
I'm the phone model im using is the TMAF025G the only things I've downloaded is the manager from GitHub

**Comment by wingio** [comment]
i don't think this is an issue i can solve, your device is blocking access to the apps own storage

**Comment by lazerl0rd** [comment]
I'm having the same issue on a Pixel 7 Pro running Android 14. I've attached the log below:

```
Vendetta Manager v1.0.89
Built from commit d4fe3b4 on main (Changes Present)

Running Android 14, API level 34
Supported ABIs: arm64-v8a

Checking if base-193013.apk is cached
base-193013.apk is not cached, downloading now

Failed on step DL_BASE_APK

java.lang.SecurityException: dev.beefers.vendetta.manager: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at dev.beefers.vendetta.manager.domain.manager.DownloadManager.download(DownloadManager.kt:100)
	at dev.beefers.vendetta.manager.domain.manager.DownloadManager.downloadDiscordApk(DownloadManager.kt:23)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.install(InstallerViewModel.kt:183)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.access$install(InstallerViewModel.kt:41)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel$job$1$1.invokeSuspend(InstallerViewModel.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
	at android.os.Binder.execTransactInternal(Binder.java:1339)
	at android.os.Binder.execTransact(Binder.java:1275)
```
