### ISSUE TITLE
Vendetta Manager fails to download base APK.

### ISSUE THREAD

**Issue by lzlrd** [vendetta-mod/Vendetta#149]
Trying to install Vendetta via Vendetta Manager results in an early failure with the following error log:

```
Vendetta Manager v1.0.89
Built from commit d4fe3b4 on main (Changes Present)

Running Android 14, API level 34
Supported ABIs: arm64-v8a

Checking if base-193013.apk is cached
base-193013.apk is not cached, downloading now

Failed on step DL_BASE_APK

java.lang.SecurityException: dev.beefers.vendetta.manager: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at dev.beefers.vendetta.manager.domain.manager.DownloadManager.download(DownloadManager.kt:100)
	at dev.beefers.vendetta.manager.domain.manager.DownloadManager.downloadDiscordApk(DownloadManager.kt:23)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.install(InstallerViewModel.kt:183)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.access$install(InstallerViewModel.kt:41)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel$job$1$1.invokeSuspend(InstallerViewModel.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
	at android.os.Binder.execTransactInternal(Binder.java:1339)
	at android.os.Binder.execTransact(Binder.java:1275)
```

**Comment by lazerl0rd** [comment]
https://stackoverflow.com/questions/76473077/in-app-update-apps-crash-in-android-14-due-to-receiver-exported-or-receiver-not

**Comment by lzlrd** [comment]
https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported

**Comment by lzlrd** [comment]
This seems to be fixed as of https://github.com/vendetta-mod/VendettaManager/commit/393a894bdd1d0d4d47b4ff583c4f52b01aba92ce. Thanks!

**Comment by wingio** [comment]
I would have closed this sooner but i thought it was in the manager repo
