### ISSUE TITLE
Failed To Load Vendetta since v202.4/v202.5 (Canary)

### ISSUE THREAD

**Issue by Kitosight** [vendetta-mod/Vendetta#169]
![Screenshot_20231020-140842.png](https://github.com/vendetta-mod/Vendetta/assets/70456337/c2c994e2-26ed-4d1a-875c-73cad4084529)

![Screenshot_20231020-140851.png](https://github.com/vendetta-mod/Vendetta/assets/70456337/8190545d-8b72-4761-893a-76552108ef1c)

**Comment by JunkiEDM** [comment]
Same here, here's the error in text form (via textbender)
```
Failed to load Vendetta!

Build Number: 202205
Vendetta: 2cc1f8d
TypeError: undefined is not a function
    at ?anon_0_?anon_0_ln (Vendetta:2:1029)
    at next (native)
    at anonymous (/tmp/tmp3dxsp38q/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5w36155w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:610:30)
    at step (/tmp/tmp3dxsp38q/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5w36155w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:595:23)
    at anonymous (/tmp/tmp3dxsp38q/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5w36155w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:609:17)
    at tryCallOne (/tmp/tmp3dxsp38q/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5w36155w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/tmp/tmp3dxsp38q/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5w36155w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (/discord/discord_android_rn/android/app/src/main/assets/index.android.bundle:165:2034)
    at _callTimer (/discord/discord_android_rn/android/app/src/main/assets/index.android.bundle:165:575)
    at _callReactNativeMicrotasksPass (/discord/discord_android_rn/android/app/src/main/assets/index.android.bundle:165:1017)
    at callReactNativeMicrotasks (/discord/discord_android_rn/android/app/src/main/assets/index.android.bundle:165:3831)
    at __callReactNativeMicrotasks (/discord/discord_android_rn/android/app/src/main/assets/index.android.bundle:48:3309)
    at anonymous (/discord/discord_android_rn/android/app/src/main/assets/index.android.bundle:48:1164)
    at __guard (/discord/discord_android_rn/android/app/src/main/assets/index.android.bundle:48:2908)
    at flushedQueue (/discord/discord_android_rn/android/app/src/main/assets/index.android.bundle:48:1122)
    at invokeCallbackAndReturnFlushedQueue (/discord/discord_android_rn/android/app/src/main/assets/index.android.bundle:48:1044)
```

**Comment by JunkiEDM** [comment]
It's worth noting that, at least on my end, after dismissing the error dialog, everything including Vendetta + its plugins seems to be working fine?
