### ISSUE TITLE
Vendetta just crashing without doing anything.

### ISSUE THREAD

**Issue by imyozen** [vendetta-mod/Vendetta#173]
Using a Samsung Galaxy A13
One UI v5.1
Android v13

After rebooting my phone this crash issue also appeared after I reinstalled discord v200.13 then I install beta or alpha but same issue.

**Comment by skdaddles** [comment]
Hey! I have the exact same phone! fully updated! Same problem here, it was working and after my phone ran out of battery, i cannot launch the app. It opens, does the loading like for every app and then it crashes. Idk what's going on but its no good.

**Comment by Brian2po** [comment]
I have the same problem, it just crashes, my theory here is that the latest discord update broke all of the modded client. We will just have to patiently wait for the fix.

**Comment by maisymoe** [comment]
Likely caused by NoTrack, I'll disable it for now and look at fixing it again later.

**Comment by nexpid** [comment]
turns out NoTrack was the source of my crashing too lol

**Comment by imyozen** [comment]
@maisymoe Please fix it soon because I'm missing vendetta🥺🥺

**Comment by nexpid** [comment]
> @maisymoe Please fix it soon because I'm missing vendetta🥺🥺

did you try uninstalling NoTrack (if you even had it installed)

**Comment by imyozen** [comment]
> > @maisymoe Please fix it soon because I'm missing vendetta🥺🥺
> 
> did you try uninstalling NoTrack (if you even had it installed)

I have not installed NoTrack

**Comment by 1Lucas1apk** [comment]
> Using a Samsung Galaxy A13
> One UI v5.1
> Android v13
> 
> After rebooting my phone this crash issue also appeared after I reinstalled discord v200.13 then I install beta or alpha but same issue.

Mine is the same thing, I managed to catch the error:

Error: FATAL EXCEPTION: create_react_context
Process: dev.beefers.vendetta, PID: 15747
java.lang.UnsatisfiedLinkError: No implementation found for void com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(android.content.res.AssetManager, java.lang.String, boolean) (tried Java_com_facebook_react_bridge_CatalystInstanceImpl_jniLoadScriptFromAssets and Java_com_facebook_react_bridge_CatalystInstanceImpl_jniLoadScriptFromAssets__Landroid_content_res_AssetManager_2Ljava_lang_String_2Z) - is the library loaded, e.g. System.loadLibrary?
    at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
    at java.lang.reflect.Method.invoke(Native Method)
    at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
    at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:474)
    at LSPHooker_.jniLoadScriptFromAssets(Unknown Source:21)
    at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(SourceFile:3)
    at com.facebook.react.bridge.JSBundleLoader$1.loadScript(SourceFile:11)
    at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(SourceFile:19)
    at com.facebook.react.ReactInstanceManager.createReactContext(SourceFile:224)
    at com.facebook.react.ReactInstanceManager.i(Unknown Source:0)
    at com.facebook.react.ReactInstanceManager$5.run(SourceFile:70)
    at java.lang.Thread.run(Thread.java:1012)

**Comment by 1Lucas1apk** [comment]
Mine is Samsung A13 (Both 5G and without, I have both devices) Android 13, One UI 5.1

**Comment by 1Lucas1apk** [comment]
Application I used to catch errors (Scoop) :)

**Comment by imyozen** [comment]
Why are you not solving this problem?
@nexpid @maisymoe

**Comment by maisymoe** [comment]
> Why are you not solving this problem?

Don't own the device, and the bug should never even occur in the first place. A device update is also more than likely to fix this in future.

**Comment by 1Lucas1apk** [comment]
Hello, I just wanted to tell those who have the A13 that a new version of Android is coming that can change the architecture from 32 bit to 64 bit because Google retired 32 bit and will probably correct this error

Until then, we have to live without Vendetta :(
