### ISSUE TITLE
GrapheneOS Crash

### ISSUE THREAD

**Issue by GGORG0** [vendetta-mod/Vendetta#65]
```
type: crash
osVersion: google/oriole/oriole:13/TQ2A.230405.003.E1/2023041100:user/release-keys
package: dev.beefers.vendetta:173023
process: dev.beefers.vendetta
processUptime: 606 + 181 ms

android.os.DeadSystemRuntimeException: android.os.DeadSystemException
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:211)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.Applicatio
[TRUNCATED 32249 CHARS]
cel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:72)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4522)
	at android.content.pm.PackageManager.getPackageInfoAsUserUncached(PackageManager.java:10496)
	at android.content.pm.PackageManager.-$$Nest$smgetPackageInfoAsUserUncached(Unknown Source:0)
	at android.content.pm.PackageManager$2.recompute(PackageManager.java:10509)
	at android.content.pm.PackageManager$2.recompute(PackageManager.java:10506)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:999)
	at android.content.pm.PackageManager.getPackageInfoAsUserCached(PackageManager.java:10523)
	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:250)
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:215)
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:209)
	at t9.i.d(SourceFile:127)
	at t9.g.f(SourceFile:1)
	at t9.f.f(Unknown Source:0)
	at w9.h0.b(SourceFile:61)
	at com.google.android.gms.common.api.internal.t.E(SourceFile:42)
	at com.google.android.gms.common.api.internal.c.j(SourceFile:36)
	at com.google.android.gms.common.api.internal.c.handleMessage(SourceFile:403)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.DeadSystemException
	... 631 more

```

Right after opening the app.

**Comment by maisymoe** [comment]
Install Vendetta in Work profile. This is an incompatibility between Sandboxed Play Services and LSPatch, the techology we use for embedding an Xposed module into an APK.

**Comment by GGORG0** [comment]
Oh it actually works when I install it in guest mode. Will try in Work soon.


Gosh how did you reply that quickly?? Thats the fastest ever reply I've gotten on an issue.

**Comment by maisymoe** [comment]
I saw your issue on the webhook we have in the Discord :)

**Comment by srappan** [comment]
Apologies for hijacking this issue. My work profile also has Google play services sandboxed, is guest mode the only alternative?

**Comment by srappan** [comment]
Apologies for hijacking this issue. My work profile also has Google play services sandboxed, is guest mode the only alternative?

Guest mode works, it's more of workaround than a solution ion to the issue
